apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      components: rabbitmq
  template:
    metadata:
      labels:
        components: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.12-management
        resources:
          limits:
            memory: "500Mi"
            cpu: "300m"
          requests:
            memory: "500Mi"
            cpu: "300m"
        ports:
        - containerPort: 15691
        - containerPort: 15692
        - containerPort: 15672
        - containerPort: 25672
        - containerPort: 4369
        - containerPort: 5671
        - containerPort: 5672
        env:
          - name: SEED_USERNAME
            value: rabbitmq
          - name: SEED_USER_PASSWORD
            value: rabbitmq
        volumeMounts:
          - name: rabbitmq-data
            mountPath: /var/lib/rabbitmq
            # subPath: postgres
      volumes:
        - name: rabbitmq-data
          persistentVolumeClaim:
            claimName: rabbitmq-pvc
