apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-api
spec:
  selector:
    matchLabels:
      app: conv-api
  template:
    metadata:
      labels:
        app: conv-api
    spec:
      containers:
        - name: conv-api
          image: antonlarichev/conv-api:v1.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
            requests:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 80
          env:
            - name: AMQP_EXCHANGE
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: AMQP_EXCHANGE
            - name: AMQP_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: AMQP_HOSTNAME
            - name: AMQP_USER
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: AMQP_USER
            - name: AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: AMQP_PASSWORD
          volumeMounts:
            - name: conv-api-pvc
              mountPath: /opt/app/uploads
      volumes:
        - name: conv-api-pvc
          persistentVolumeClaim:
            claimName: conv-api-pvc
            

